export default interface IStudentDetails{
    "asAcademicYearId":string,
    "asSchoolId":string,
    "asStandardId":string,
    "asDivisionId":string,
    "asUserId":string,
    "asUserRoleId":String,
    "abIsSMSCenter":string,
    "asFilter":string,
    "asFlag":string,
    "asMonthId":string,
    "asPageIndex":string,
    "asMessageRecieverDetailsId":string,
    "asMessageDetailsId":string,
    "asIsCompeteDelete":string,
    "asReceiverUserRoleId":string,
    "asSMSId":string,
    "asNoticeId":string
}